In [3]:
import numpy as np

In [4]:
a = np.random.randn(5)

In [7]:
print(a)

[ 0.61587498  0.52243149 -1.50145387  0.37906829  0.21427231]


In [5]:
print(a.shape)

(5,)


In [6]:
print(a.T)  

[ 0.61587498  0.52243149 -1.50145387  0.37906829  0.21427231]


In [8]:
print(np.dot(a, a.T))

3.0962057632275912


In [11]:
b = np.random.randn(3,1)
print(b)

[[ 1.45904521]
 [-0.13542457]
 [ 0.7172284 ]]


In [12]:
print(b.T)

[[ 1.45904521 -0.13542457  0.7172284 ]]


In [13]:
print(np.dot(b, b.T))

[[ 2.12881291 -0.19759058  1.04646866]
 [-0.19759058  0.01833982 -0.09713035]
 [ 1.04646866 -0.09713035  0.51441658]]


In [14]:
# Use if you are not sure of the dimensions of the array
assert(b.shape == (3,1))
# Alternatively , use reshape to get the shape you want  